import { createApi, fakeBaseQuery } from "@reduxjs/toolkit/query/react";
import type { Page } from "../types/guide";
import { v4 as uuid } from "uuid";

/***This simulates a database in memory*/
let pages: Page[] = [
    {
    id: uuid(),
    title: "Getting Started",
    sections: [],
    },
];
/*** Types for addSection mutation*/
type AddSectionResponse = {
    pageId: string;
    sectionId: string;
};
type AddSectionArgs = {
    pageId: string;
    title: string;
};

export const api = createApi({
    reducerPath: "api",
    baseQuery: fakeBaseQuery(),
    tagTypes: ["Pages"],
    endpoints: (builder) => ({
    /*** GET /pages*/
    getPages: builder.query<Page[], void>({
        queryFn: async () => {
        return { data: pages };
        },
        providesTags: ["Pages"],
    }),
    /*** POST /pages*/
    createPage: builder.mutation<Page, { title: string }>({
        queryFn: async ({ title }) => {
        const newPage: Page = {
            id: uuid(),
            title,
            sections: [],
        };
        pages.push(newPage);
        return { data: newPage };
        },
        invalidatesTags: ["Pages"],
    }),
    /*** POST /pages/:pageId/sections*/
    addSection: builder.mutation<AddSectionResponse, AddSectionArgs>({
        queryFn: async ({ pageId, title }) => {
        const page = pages.find((p) => p.id === pageId);
        if (!page) {
            return {
            error: {
                status: 404,
                data: "Page not found",
            } as any,
            };
        }
        const newSection = {
            id: uuid(),
            title,
            blocks: [],
        };
        page.sections.push(newSection);
        return {
            data: {
            pageId,
            sectionId: newSection.id,
            },
        };
        },
        invalidatesTags: ["Pages"],
    }),
    }),
});

/***Hooks generated by RTK Query*/
export const {
    useGetPagesQuery,
    useCreatePageMutation,
    useAddSectionMutation,
} = api;
